### ISSUE TITLE
`FileUtil.cp` with a link source is not posixly correct

### ISSUE THREAD

**Issue by ivg** [gildor478/ocaml-fileutils#2]
The new behavior of `FileUtil.cp` when it sees a link as a *source_file* is to use `Unix.symlink`. This contradicts with POSIX and with an actual (and intuitive) behavior of `cp`. Here is the excerpt from posix:

> If neither the -R nor -r options were specified, cp shall take actions based on the type and contents of the file referenced by the symbolic link, and not by the symbolic link itself.

The only case when symbolic link is preserved to be a link, is when a `-P` (`--no-dereference`) option is specified.

**Comment by gildor478** [comment]
Please report the bug here:
https://forge.ocamlcore.org/tracker/?atid=589&group_id=128&func=browse

You may also provide me with 1. a concrete example, so that I can easily create a test and 2. link to the POSIX doc you are quoting.

I'll close this bug in 24h (and try to figure out how to hide the issues tab in github), file it on the forge please.

**Comment by ivg** [comment]
Moved the issue to [OCaml Forge](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1649&group_id=128&atid=589).
